# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d73216332f0a60d75e96bf100cbec430ab4a6a5bcd61b19b2534b524db09df07eb09799ec149b293a6d8e776329d32a5feace0dda6d0c68afdd97abc9208546

test:
  secret_key_base: cdc205403a62fe723630ed674c0acb75c08407abeb97bfe5f8d0e6c75c0f0f8ec46225a6879ad5d22d6e0630b161f6db1f2c28fe90fcc7996595368a9f45dab6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
